### ISSUE TITLE
Crash, freeze when mixing keyboard and mouse input in the Help, Status modal windows

### ISSUE THREAD

**Issue by tristhaus** [tristhaus/CSLibreCell#1]
**Background**
It is possible to open modal windows (Help, Status) using keyboard shortcuts from the root/main window. They have `OK` buttons to close them, which are also clickable.

**Problem**
After opening such a window using the keyboard, mouse-clicking `OK` to close it leads to application crash or freezing.

**Expected Behavior**
It should be possible to open sub-windows using any method and close them using any (possibly other) method without crash, freeze or UX degradation.

**Steps to reproduce**
1. Open application
2. Optional: start a game, play a few moves
3. Press the button to open _e.g._ the Help dialog. Default: `<F1>` (alt: Status, `<F12>`)
4. Use the mouse to close the dialog by clicking the `OK` button
5. Observe crash or freeze

**Possible Cause**
Bug in `Terminal.Gui` (as used in Nuget package: version 0.90.3.0), leading to `System.NullReferenceException` with stacktrace:

    at Terminal.Gui.MenuBar.ProcessHotKey(KeyEvent kb)
    at Terminal.Gui.View.ProcessHotKey(KeyEvent keyEvent)
    at Terminal.Gui.Application.ProcessKeyEvent(KeyEvent ke)
    at Terminal.Gui.WindowsDriver.Terminal.Gui.IMainLoopDriver.MainIteration()
    at Terminal.Gui.MainLoop.MainIteration()
    at Terminal.Gui.Application.RunLoop(RunState state, Boolean wait)
    at Terminal.Gui.Application.Run(Toplevel view)
    at CSLibreCell.Program.Main() in D:\VSProject\CSharp\CSLibreCell\CSLibreCell\Program.cs:line 214

**Notes**
Using the keys to open the appropriate menu (for the Help, using the English localization: `Alt+? h`) does not yield the same problem.

**Affected versions**
v0.1.0

**Comment by tristhaus** [comment]
Possible workarounds: remove the buttons for direct access and rely on the menubar-provided shortcuts. Keep track of how the modal window was opened and remove clickability of the buttons as necessary (if technically possible to just suppress clickability).

Until the problem becomes more serious, we'll try to wait for a new `Terminal.GUI` release and adapt to accelerator keys.

**Comment by tristhaus** [comment]
Fixed via NuGet package update (https://github.com/tristhaus/CSLibreCell/commit/592d586236f1a340eb092fa3b0854af91bc54406). Released in v0.4.0.
